import { ThemeProvider } from "@/services/theme";
import "./globals.css";
import "animate.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSans = Open_Sans({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Milan Haria",
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${openSans.className} min-h-screen mx-auto text-black dark:text-white bg-gradient-to-b from-blue-50 to-white dark:from-gray-800  dark:to-gray-900 overflow-x-hidden`}
        >
          {children}
          <section className="w-full pt-24 pb-12 text-sm tracking-wide text-center uppercase">
            <span>All Rights Reserved © Milan Haria 2023</span>
          </section>
        </body>
      </ThemeProvider>
    </html>
  );
}
